### ISSUE TITLE
Formato do material

### ISSUE THREAD

**Issue by juniormartinxo** [cerebrobr/cursos#2]
Levando-se em conta o tamanho máximo dos arquivos exigidos pelo GitHub (~50MB), qual seria o formato dos materiais, seriam vídeos, apostilas, slides, qualquer formato? Ficariam hospedados neste repo mesmo?

**Comment by thulioph** [comment]
Olá @mjpsolucoes, obrigado pelo interesse em colaborar para o **Cerebro**.
Atualmente não estamos disponibilizando materiais "físicos", caso você tenha um link de algum material seja ele vídeo, slide, apostila, etc é só disponibiliza-lo que iremos revisar e ele será aceito.

**Comment by vitorbritto** [comment]
@mjpsolucoes o material é por referência (via link). Para contribuir, basta fazer o _fork_ do repositório, contribuir com os links desejados e fazer um _pull request_ de acordo com o [Guia de Contribuição](https://github.com/cerebrobr/cerebro/blob/master/README.md) da organização. =]

**Comment by juniormartinxo** [comment]
@thulioph e @vitorbritto obrigado e seguirei as orientações!
